Add linked_spaces attribute
SpaceApi/schema pull request #75
Opened 2020-05-16 21:11 UTC by gidsi

I would go with the spaces website, I've named it according to the SpaceAPI field.

Discussion can be found in [issue 144](https://github.com/SpaceApi/directory/issues/144) and in the [meeting notes](https://github.com/SpaceApi/meeting-notes/blob/master/20200510-telco.md#5-decentralized-directory)

2020-08-09 18:55 UTC, rnestler commented on 14-draft.json
> +          "endpoint"
Shouldn't this be "url"?

2020-08-10 09:34 UTC, dbrgn commented on 14-draft.json
> +            "description": "The spaces website according to their SpaceAPI endpoint",
I assume you meant `the space's`. Alternatively, `the space website`.

2021-01-10 18:15 UTC, dbrgn requested changes
LGTM!

However, can you update the PR to point to `v15-draft.json`?

2021-01-10 20:15 UTC, dbrgn approved these changes

2021-01-10 20:18 UTC, s3lph approved these changes
🚀

2021-01-10 20:18 UTC, merged